[package]
name = "business-installer"
version = "1.0.0"
edition = "2021"

[lib]
name = "business_installer"
path = "src/lib.rs"

[features]
default = ["debugger"]
debugger = ["liana-gui/debugger"]

[dependencies]
crossbeam-channel = "0.5"
minreq = { workspace = true }
iced = { workspace = true, default-features = false, features = ["thread-pool", "image-without-codecs", "tiny-skia", "x11", "wayland"] }
liana = { workspace = true }
liana-connect = { workspace = true }
liana-gui = { workspace = true, features = ["skip-windows-icon"] }
liana-ui = { workspace = true }
miniscript = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
rustls = { workspace = true, features = ["ring"] }
bwk-hwi = { workspace = true, features = ["service", "ledger", "jade", "coldcard", "bitbox", "specter"] }
tracing = { workspace = true }
futures = { workspace = true }
hex = "0.4"
